import type { Metadata } from "next";
import "./globals.css";
import { Poppins, Gabarito } from "next/font/google";

const poppinsSans = Poppins({
  variable: "--font-body",
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
  display: "swap",
});

const gabaritoSans = Gabarito({
  variable: "--font-heading",
  weight: ["500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${poppinsSans.variable} ${gabaritoSans.variable} antialiased`} >
        {children}
      </body>
    </html>
  );
}
