# @format

name: CI Testing
on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: CI Testing
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Integration Tests
        run: npm test
        env:
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          NEON_PROJECT_ID: ${{ vars.NEON_PROJECT_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL_DEV }}
